# Generated by Django 4.1.7 on 2023-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_rename_tbl_internships_tbl_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_title', models.CharField(max_length=50)),
                ('plc_designation', models.CharField(max_length=50)),
                ('plc_date', models.DateField(auto_now=True)),
                ('plc_salary', models.CharField(max_length=50)),
                ('plc_details', models.TextField(null=True)),
            ],
        ),
    ]
