# Generated by Django 4.1.7 on 2023-03-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_tbl_placements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_placements',
            name='plc_salary',
            field=models.IntegerField(default=0),
        ),
    ]
