# Generated by Django 4.1.7 on 2023-03-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_companyregistration_company_vsts_and_more'),
        ('Company', '0004_alter_tbl_placements_plc_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_internship',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.companyregistration'),
        ),
        migrations.AddField(
            model_name='tbl_placements',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.companyregistration'),
        ),
    ]
