# Generated by Django 4.1.7 on 2023-03-06 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_designation'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_contact', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_address', models.TextField(null=True)),
                ('company_logo', models.FileField(upload_to='userdocs/')),
                ('company_proof', models.FileField(upload_to='userdocs/')),
                ('company_password', models.CharField(max_length=100, unique=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
