# Generated by Django 4.1.7 on 2023-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_companyregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='company_logo',
            field=models.FileField(upload_to='companydocs/'),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='company_proof',
            field=models.FileField(upload_to='companydocs/'),
        ),
    ]
