# Generated by Django 4.1.7 on 2023-03-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_companyregistration_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='company_vsts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_vsts',
            field=models.IntegerField(default=0),
        ),
    ]
