# Generated by Django 4.1.7 on 2023-03-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0005_tbl_internship_company_tbl_placements_company'),
        ('Guest', '0004_companyregistration_company_vsts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now=True)),
                ('plcapply_sts', models.IntegerField(default=0)),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.tbl_placements')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Intership_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now=True)),
                ('intapply_sts', models.IntegerField(default=0)),
                ('internship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.tbl_internship')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
            ],
        ),
    ]
