# Generated by Django 4.1.7 on 2023-03-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_tbl_internship_company_tbl_placements_company'),
        ('Guest', '0004_companyregistration_company_vsts_and_more'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intership_Apply',
            new_name='Internship_Apply',
        ),
    ]
